// flow-typed signature: 72070ad84b63c0ee7e7b7bf4f10456dd
// flow-typed version: <<STUB>>/jwks-rsa_v^2.0.1/flow_v0.126.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jwks-rsa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jwks-rsa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jwks-rsa/src/errors/ArgumentError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/errors' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/errors/JwksError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/errors/JwksRateLimitError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/errors/SigningKeyNotFoundError' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/integrations/config' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/integrations/express' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/integrations/hapi' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/integrations/koa' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/integrations/passport' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/JwksClient' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/utils' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/wrappers/cache' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/wrappers/callbackSupport' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/wrappers' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/wrappers/interceptor' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/wrappers/rateLimit' {
  declare module.exports: any;
}

declare module 'jwks-rsa/src/wrappers/request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jwks-rsa/src/errors/ArgumentError.js' {
  declare module.exports: $Exports<'jwks-rsa/src/errors/ArgumentError'>;
}
declare module 'jwks-rsa/src/errors/index' {
  declare module.exports: $Exports<'jwks-rsa/src/errors'>;
}
declare module 'jwks-rsa/src/errors/index.js' {
  declare module.exports: $Exports<'jwks-rsa/src/errors'>;
}
declare module 'jwks-rsa/src/errors/JwksError.js' {
  declare module.exports: $Exports<'jwks-rsa/src/errors/JwksError'>;
}
declare module 'jwks-rsa/src/errors/JwksRateLimitError.js' {
  declare module.exports: $Exports<'jwks-rsa/src/errors/JwksRateLimitError'>;
}
declare module 'jwks-rsa/src/errors/SigningKeyNotFoundError.js' {
  declare module.exports: $Exports<'jwks-rsa/src/errors/SigningKeyNotFoundError'>;
}
declare module 'jwks-rsa/src/index' {
  declare module.exports: $Exports<'jwks-rsa/src'>;
}
declare module 'jwks-rsa/src/index.js' {
  declare module.exports: $Exports<'jwks-rsa/src'>;
}
declare module 'jwks-rsa/src/integrations/config.js' {
  declare module.exports: $Exports<'jwks-rsa/src/integrations/config'>;
}
declare module 'jwks-rsa/src/integrations/express.js' {
  declare module.exports: $Exports<'jwks-rsa/src/integrations/express'>;
}
declare module 'jwks-rsa/src/integrations/hapi.js' {
  declare module.exports: $Exports<'jwks-rsa/src/integrations/hapi'>;
}
declare module 'jwks-rsa/src/integrations/koa.js' {
  declare module.exports: $Exports<'jwks-rsa/src/integrations/koa'>;
}
declare module 'jwks-rsa/src/integrations/passport.js' {
  declare module.exports: $Exports<'jwks-rsa/src/integrations/passport'>;
}
declare module 'jwks-rsa/src/JwksClient.js' {
  declare module.exports: $Exports<'jwks-rsa/src/JwksClient'>;
}
declare module 'jwks-rsa/src/utils.js' {
  declare module.exports: $Exports<'jwks-rsa/src/utils'>;
}
declare module 'jwks-rsa/src/wrappers/cache.js' {
  declare module.exports: $Exports<'jwks-rsa/src/wrappers/cache'>;
}
declare module 'jwks-rsa/src/wrappers/callbackSupport.js' {
  declare module.exports: $Exports<'jwks-rsa/src/wrappers/callbackSupport'>;
}
declare module 'jwks-rsa/src/wrappers/index' {
  declare module.exports: $Exports<'jwks-rsa/src/wrappers'>;
}
declare module 'jwks-rsa/src/wrappers/index.js' {
  declare module.exports: $Exports<'jwks-rsa/src/wrappers'>;
}
declare module 'jwks-rsa/src/wrappers/interceptor.js' {
  declare module.exports: $Exports<'jwks-rsa/src/wrappers/interceptor'>;
}
declare module 'jwks-rsa/src/wrappers/rateLimit.js' {
  declare module.exports: $Exports<'jwks-rsa/src/wrappers/rateLimit'>;
}
declare module 'jwks-rsa/src/wrappers/request.js' {
  declare module.exports: $Exports<'jwks-rsa/src/wrappers/request'>;
}
